if __name__ == '__main__':
    text = "light   ray"
    print(text[-1])
    print(text[0:2])
    print(text[0:5:2])
    print(text[:5])
    print(text[5:])
    print(text[::2])
    print(text[::-2])
    print(text[::-1])
    print(text.capitalize())
    print(text.index("ray"))
    print("qwei123".isalnum())
    print("qwer".isalpha())
    print("12312".isdecimal())
    print("1234455".isdigit())
    print("123123".isnumeric())
    print(text.center(3, "#"))
    print(text.ljust(3, "*"))
    print(text.join("-"))
    print("-".join(text.split()))
    print("*" * 8)
    table = "".maketrans("一二三","123")
    tran_result = "一 二 三".translate(table)
    print(tran_result)
    print(hex(ord("一")))

